export {default as Main} from './Main';
export {default as Datasets} from './Datasets';
export {default as Code} from './Code';
export {default as Upload} from './Upload';
export {default as Library} from './Library';
export {default as Docs} from './Docs';
export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as FindPW} from './FindPW';
export {default as Datasetsdetail } from './Datasetsdetail';
export {default as Codedetail } from './Codedetail';
